# Sesión 5 Introducción a Random

In [2]:
import numpy as np

### Choice

In [3]:
np.random.choice(5, 3)

array([3, 1, 0])

In [4]:
np.random.choice(5, 3)

array([3, 2, 0])

In [5]:
np.random.choice(5, 3)

array([0, 2, 4])

In [6]:
np.random.choice(100, 3)

array([20, 88, 29])

In [7]:
np.random.choice(10, 5, replace=False)

array([3, 9, 5, 6, 4])

In [9]:
np.random.permutation(10)

array([6, 1, 4, 2, 5, 9, 7, 8, 0, 3])

### Permutation

In [10]:
np.random.permutation(50)

array([12,  9, 13, 19, 18, 34, 38, 37, 25, 10, 23, 46, 48, 43, 40, 29, 11,
        1,  0, 36, 21, 42,  2, 31, 35, 33, 41, 22,  6, 26, 45, 17, 24, 44,
       30,  3, 16, 14,  8,  7, 49, 28,  5, 15, 47,  4, 20, 27, 32, 39])

### Rand

Valores aleatorios en una forma dada.

In [23]:
np.random.rand(3)

array([0.86037127, 0.25765464, 0.70418768])

In [22]:
np.random.rand(3,2)

array([[0.7538241 , 0.95944928],
       [0.07012321, 0.33062319],
       [0.76361758, 0.21308858]])

### Randint

Devuelve números enteros aleatorios de bajo (inclusivo) a alto (exclusivo).

Devuelve números enteros aleatorios de la distribución "uniforme discreta" del tipo de d especificado en el intervalo "medio abierto" [bajo, alto]. Si alto es Ninguno (el valor predeterminado), los resultados son de [0, bajo).

In [25]:
np.random.randint(20, size=10)

array([19,  6, 17,  8,  4,  6,  1,  8,  4, 16])

In [26]:
np.random.randint(5, size=(2, 4))

array([[0, 0, 0, 4],
       [0, 1, 4, 0]])

In [32]:
np.random.randint(10, 20)

14

In [30]:
np.random.randint(0, 15, 20)

array([14,  7,  4,  0,  0,  9,  5,  5,  6,  8,  7,  9,  2, 12,  4,  2, 13,
        3, 14, 10])

In [31]:
np.random.randint(10, size=(3, 3))

array([[8, 3, 5],
       [7, 8, 0],
       [5, 2, 4]])

### Suffle

Modifique una secuencia en el lugar mezclando su contenido.

Esta función solo baraja la matriz a lo largo del primer eje de una matriz multidimensional. Se cambia el orden de los subconjuntos, pero su contenido sigue siendo el mismo.

In [42]:
arr = np.arange(10)

np.random.shuffle(arr)

arr

array([6, 1, 7, 0, 4, 2, 9, 3, 8, 5])

np.random.permutation tiene dos diferencias con np.random.shuffle:

    si se pasa una matriz, devolverá una copia mezclada de la matriz; np.random.shuffle baraja la matriz en su lugar
    si se pasa un número entero, devolverá un rango aleatorio, es decir, np.random.shuffle(np.arange(n))

    Si x es un número entero, permute aleatoriamente np.arange(x). Si x es una matriz, haz una copia y mezcla los elementos al azar.

In [43]:
np.random.permutation(10)

array([2, 4, 8, 9, 3, 0, 1, 6, 7, 5])

In [46]:
np.random.randint(10, size=10)

array([8, 1, 4, 5, 4, 1, 2, 7, 9, 3])

## Método Flip

In [13]:
array = np.array([1,2,3,4,5])

In [14]:
np.flip(array)

array

array([1, 2, 3, 4, 5])

## Lambda

In [17]:
def doble(x):
    return x*2

In [18]:
doble(5)

10

In [20]:
doble = lambda x: x*2

In [21]:
doble(5)

10

In [33]:
raiz = lambda numero: numero ** 0.5

In [34]:
raiz (9)

3.0

In [35]:
resta = lambda n1, n2: n1 -n2

In [36]:
resta(5, 6)

-1